# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
jobs:
  build:
    docker:
      - image: circleci/node:14.15.4-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm install --global yarn
      - run: yarn install
      - run: yarn test