# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
jobs:
  build:
    docker:
      - image: cimg/node:1.22.10
    steps:
      - checkout
      - run: yarn --version
      - run: yarn start
      - run: yarn test