# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
jobs:
  build:
    docker:
      - image: cimg/node:<version>-browsers
    steps:
      - checkout
      - run: node --version
      - run: yarn install
      - run: yarn start