# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: cd
          command: cd client
      - run: 
          name: pwd
          command: pwd
      - run: 
          name: ls
          command: ls
      - run:
          name: Update NPM
          command: cd client && "sudo npm install -g npm@6.14.10"
      - run:
          name: Install Dependencies
          command: cd client && npm install --no-package-lock
      - run:
          name: Install Yarn
          command: cd client && yarn install
      - run:
          name: Run tests
          command: cd client && yarn test

