# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo/client
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout:
          path: ~/repo/client
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@6.14.10"
      - run:
          name: Install Dependencies
          command: npm install --no-package-lock
      - run:
          name: Install Yarn
          command: yarn install
      - run:
          name: Run tests
          command: yarn test

